// This file is generated by `npm run gen:api` using openapi-typescript.
// Do not edit manually. If you need to change types, update the backend OpenAPI spec.
// Placeholder minimal export to keep typecheck green before generation.
export type components = unknown;
export type paths = unknown;
export type operations = unknown;
